// <auto-generated />
using System;
using ComparacaoPropostas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComparacaoPropostas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813094340_ItemPedidoLigaAPedidoProposta")]
    partial class ItemPedidoLigaAPedidoProposta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CriterioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PropostaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriterioId");

                    b.HasIndex("PropostaId", "CriterioId")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Criterios");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemCore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItensCore");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemEnergia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItensEnergia");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemFbb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItensFbb");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemPaiId")
                        .HasColumnType("int");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemPaiId");

                    b.ToTable("ItensMaterial");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemMbb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dominio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItensMbb");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoPropostaId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeSolicitada")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMaterialId");

                    b.HasIndex("PedidoPropostaId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemProposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Incluido")
                        .HasColumnType("bit");

                    b.Property<int>("ItemMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropostaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("QuantidadeSolicitada")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMaterialId");

                    b.HasIndex("PropostaId");

                    b.ToTable("ItensProposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.PedidoProposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PessoaCriou")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoProposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailsNotificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OrcamentoEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PedidoPropostaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrazoFinal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoPropostaId")
                        .IsUnique();

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Proposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrazoEntregaDias")
                        .HasColumnType("int");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ValidadeProposta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Propostas");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.PropostaAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropostaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropostaId");

                    b.ToTable("PropostasAnexo");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Avaliacao", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.Criterio", "Criterio")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("CriterioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComparacaoPropostas.Models.Entities.Proposta", "Proposta")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterio");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Criterio", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.Processo", "Processo")
                        .WithMany("Criterios")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemMaterial", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.ItemMaterial", "ItemPai")
                        .WithMany("SubItens")
                        .HasForeignKey("ItemPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ItemPai");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemPedido", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.ItemMaterial", "ItemMaterial")
                        .WithMany()
                        .HasForeignKey("ItemMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComparacaoPropostas.Models.Entities.PedidoProposta", "PedidoProposta")
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoPropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaterial");

                    b.Navigation("PedidoProposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemProposta", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.ItemMaterial", "ItemMaterial")
                        .WithMany("ItensProposta")
                        .HasForeignKey("ItemMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComparacaoPropostas.Models.Entities.Proposta", "Proposta")
                        .WithMany("ItensProposta")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMaterial");

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Processo", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.PedidoProposta", "PedidoProposta")
                        .WithOne("Processo")
                        .HasForeignKey("ComparacaoPropostas.Models.Entities.Processo", "PedidoPropostaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PedidoProposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Proposta", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.Processo", "Processo")
                        .WithMany("Propostas")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.PropostaAnexo", b =>
                {
                    b.HasOne("ComparacaoPropostas.Models.Entities.Proposta", "Proposta")
                        .WithMany("Anexos")
                        .HasForeignKey("PropostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Criterio", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.ItemMaterial", b =>
                {
                    b.Navigation("ItensProposta");

                    b.Navigation("SubItens");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.PedidoProposta", b =>
                {
                    b.Navigation("ItensPedido");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Processo", b =>
                {
                    b.Navigation("Criterios");

                    b.Navigation("Propostas");
                });

            modelBuilder.Entity("ComparacaoPropostas.Models.Entities.Proposta", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Avaliacoes");

                    b.Navigation("ItensProposta");
                });
#pragma warning restore 612, 618
        }
    }
}
