using Microsoft.EntityFrameworkCore;
using ComparacaoPropostas.Models.Entities;
using ComparacaoPropostas.Models.Entities.Enums;

namespace ComparacaoPropostas.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Processo> Processos => Set<Processo>();
    public DbSet<Criterio> Criterios => Set<Criterio>();
    public DbSet<Proposta> Propostas => Set<Proposta>();
    public DbSet<Avaliador> Avaliadores => Set<Avaliador>();
    public DbSet<Fornecedor> Fornecedores => Set<Fornecedor>();
    public DbSet<MemoriaCalculoAvaliacao> MemoriaCalculoAvaliacao => Set<MemoriaCalculoAvaliacao>();
    public DbSet<Avaliacao> Avaliacoes => Set<Avaliacao>();
    public DbSet<ItemMaterial> ItensMaterial => Set<ItemMaterial>();
    public DbSet<ItemProposta> ItensProposta => Set<ItemProposta>();
    public DbSet<PropostaAnexo> PropostasAnexo => Set<PropostaAnexo>();
    public DbSet<PedidoProposta> Pedidos => Set<PedidoProposta>();
    public DbSet<ItemPedido> ItensPedido => Set<ItemPedido>();

    // Base de Dados — catálogos independentes por área, ainda sem ligação a
    // Propostas/Pedidos (fica para uma alteração futura).
    public DbSet<ItemEnergia> ItensEnergia => Set<ItemEnergia>();
    public DbSet<ItemMbb> ItensMbb => Set<ItemMbb>();
    public DbSet<ItemFbb> ItensFbb => Set<ItemFbb>();
    public DbSet<ItemCore> ItensCore => Set<ItemCore>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Processo>(e =>
        {
            e.Property(p => p.NumeroProcesso).HasMaxLength(30).HasDefaultValue("");
            e.Property(p => p.Status).HasConversion<string>().HasMaxLength(20);
            e.Property(p => p.TipoCompra).HasConversion<string>().HasMaxLength(20).HasDefaultValue(TipoCompra.Nacional);
            e.Property(p => p.TaxaCambioPadrao).HasPrecision(18, 4);
            e.Property(p => p.ValorAdjudicado).HasPrecision(18, 2);
            e.Property(p => p.ValorAdjudicadoMoeda).HasMaxLength(10);
            e.Property(p => p.ValorAdjudicadoCVE).HasPrecision(18, 2);
            e.Property(p => p.PontuacaoAdjudicada).HasPrecision(5, 2);

            // 1-1: a Processo is always generated by exactly one PedidoProposta.
            e.HasOne(p => p.PedidoProposta)
                .WithOne(pp => pp.Processo)
                .HasForeignKey<Processo>(p => p.PedidoPropostaId)
                .OnDelete(DeleteBehavior.Restrict);

            // 1-1 opcional com a proposta adjudicada
            e.HasOne(p => p.PropostaVencedora)
                .WithMany()
                .HasForeignKey(p => p.PropostaVencedoraId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<Proposta>(e =>
        {
            e.Property(p => p.Status).HasConversion<string>().HasMaxLength(20);
            e.Property(p => p.Moeda).HasMaxLength(10);
            e.Property(p => p.TaxaCambio).HasPrecision(18, 4);
            e.Property(p => p.ValorTotal).HasPrecision(18, 2);
            e.Property(p => p.Garantia).HasMaxLength(200);

            e.HasOne(p => p.Processo)
                .WithMany(pr => pr.Propostas)
                .HasForeignKey(p => p.ProcessoId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<PedidoProposta>(e =>
        {
            e.Property(p => p.Status).HasConversion<string>().HasMaxLength(20);
            e.Property(p => p.Area).HasConversion<string>().HasMaxLength(20);
            e.Property(p => p.OrcamentoEstimado).HasPrecision(18, 2);
        });

        modelBuilder.Entity<ItemPedido>(e =>
        {
            e.Property(p => p.QuantidadeSolicitada).HasPrecision(18, 3);

            e.HasOne(ip => ip.PedidoProposta)
                .WithMany(pp => pp.ItensPedido)
                .HasForeignKey(ip => ip.PedidoPropostaId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(ip => ip.ItemMaterial)
                .WithMany()
                .HasForeignKey(ip => ip.ItemMaterialId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<Criterio>(e =>
        {
            e.Property(c => c.Peso).HasPrecision(5, 2);
            e.Property(c => c.TipoAutomatico).HasConversion<string>().HasMaxLength(20).HasDefaultValue(TipoCriterioAutomatico.Nenhum);

            e.HasOne(c => c.Processo)
                .WithMany(p => p.Criterios)
                .HasForeignKey(c => c.ProcessoId)
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<MemoriaCalculoAvaliacao>(e =>
        {
            e.Property(m => m.Nota).HasPrecision(5, 2);
            e.Property(m => m.Justificativa).HasMaxLength(500);

            e.HasOne(m => m.Proposta)
                .WithMany(p => p.MemoriaCalculo)
                .HasForeignKey(m => m.PropostaId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(m => m.Criterio)
                .WithMany()
                .HasForeignKey(m => m.CriterioId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasIndex(m => new { m.PropostaId, m.CriterioId }).IsUnique();
        });

        modelBuilder.Entity<Avaliador>(e =>
        {
            e.Property(a => a.Nome).HasMaxLength(200);
            e.Property(a => a.Perfil).HasMaxLength(100);
            e.Property(a => a.Email).HasMaxLength(200);
        });

        modelBuilder.Entity<Fornecedor>(e =>
        {
            e.Property(f => f.Nome).HasMaxLength(200);
            e.Property(f => f.Tipo).HasMaxLength(50);
            e.Property(f => f.Contribuinte).HasMaxLength(50);
            e.Property(f => f.Contacto).HasMaxLength(50);
            e.Property(f => f.Email).HasMaxLength(200);
            e.HasIndex(f => f.Nome).IsUnique();
        });

        modelBuilder.Entity<Avaliacao>(e =>
        {
            e.HasOne(a => a.Proposta)
                .WithMany(p => p.Avaliacoes)
                .HasForeignKey(a => a.PropostaId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(a => a.Criterio)
                .WithMany(c => c.Avaliacoes)
                .HasForeignKey(a => a.CriterioId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasOne(a => a.Avaliador)
                .WithMany(av => av.Avaliacoes)
                .HasForeignKey(a => a.AvaliadorId)
                .OnDelete(DeleteBehavior.Restrict);

            e.HasIndex(a => new { a.PropostaId, a.CriterioId, a.AvaliadorId }).IsUnique();
        });

        modelBuilder.Entity<ItemMaterial>(e =>
        {
            e.HasOne(im => im.ItemPai)
                .WithMany(im => im.SubItens)
                .HasForeignKey(im => im.ItemPaiId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<ItemProposta>(e =>
        {
            e.Property(p => p.Quantidade).HasPrecision(18, 3);
            e.Property(p => p.QuantidadeSolicitada).HasPrecision(18, 3);
            e.Property(p => p.PrecoUnitario).HasPrecision(18, 2);

            e.HasOne(ip => ip.Proposta)
                .WithMany(p => p.ItensProposta)
                .HasForeignKey(ip => ip.PropostaId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(ip => ip.ItemMaterial)
                .WithMany(im => im.ItensProposta)
                .HasForeignKey(ip => ip.ItemMaterialId)
                .OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<PropostaAnexo>(e =>
        {
            e.HasOne(a => a.Proposta)
                .WithMany(p => p.Anexos)
                .HasForeignKey(a => a.PropostaId)
                .OnDelete(DeleteBehavior.Cascade);
        });
    }
}
